### ISSUE TITLE
Add bi-scripts and Stellar address converter 

### ISSUE THREAD

**Issue by bogdanS98** [pendulum-chain/pendulum-tools#1]
### Context

As this repository is meant for making all our scripts available in one place, we have to add the remaining ones here ([Stellar address converter](https://github.com/gonzamontiel/stellar-address-converter/blob/master/index.js) and [bi-scripts](https://github.com/pendulum-chain/bi-scripts)).

### Requirement

Add the scripts mentioned above to this repository and delete the old repo for [bi-scripts](https://github.com/pendulum-chain/bi-scripts).
Test that scripts are working as intended once moved.

**Comment by bogdanS98** [comment]
@pendulum-chain/product This doesn't require too much effort and it's nice to have, but not urgent.

**Comment by prayagd** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/pendulum-tools/1?planning-poker) with Zenhub @b-yap @bogdanS98 @ebma @gianfra-t @TorstenStueber
